name: Tests
on:
  pull_request:
    branches: [main, develop]
  push:
    branches: [main, develop]
jobs:
  Lint-Check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run test
